"""
Dữ liệu từ vựng theo bài học (Minna no Nihongo / Sơ~Trung cấp).
Mỗi bài là một list dict với các trường:
  word, reading, hanviet, meaning, example, exampleVi
"""

VOCAB_LESSONS: dict[int, list[dict]] = {
    26: [
        {"word": "見る", "reading": "みる", "hanviet": "KIẾN", "meaning": "Xem, nhìn, kiểm tra", "example": "資料を見ていただけませんか", "exampleVi": "Bạn có thể xem qua tài liệu giúp tôi được không"},
        {"word": "診る", "reading": "みる", "hanviet": "CHẨN", "meaning": "Khám bệnh", "example": "先生に診ていただきたいんです", "exampleVi": "Tôi muốn được bác sĩ khám bệnh cho"},
        {"word": "探す", "reading": "さがす", "hanviet": "THÁM", "meaning": "Tìm, tìm kiếm (vật, người mong muốn)", "example": "いいアルバイトを探しているんです", "exampleVi": "Thật ra là tôi đang tìm một công việc làm thêm tốt"},
        {"word": "捜す", "reading": "さがす", "hanviet": "SƯU", "meaning": "Tìm, tìm kiếm (vật bị mất, tội phạm)", "example": "財布を捜しているんですか", "exampleVi": "Có phải bạn đang tìm cái ví không"},
        {"word": "遅れる", "reading": "おくれる", "hanviet": "TRÌ", "meaning": "Chậm, muộn [giờ]", "example": "時間に遅れる場合は、連絡してください", "exampleVi": "Trong trường hợp muộn giờ, hãy liên lạc nhé"},
        {"word": "間に合う", "reading": "まにあう", "hanviet": "GIAN HỢP", "meaning": "Kịp [giờ]", "example": "会議に間に合うでしょうか", "exampleVi": "Liệu có kịp giờ họp không nhỉ"},
        {"word": "やる", "reading": "やる", "hanviet": "KHIỂN", "meaning": "Làm, thực hiện, cho (cấp dưới, động vật)", "example": "猫にえさをやるのを忘れました", "exampleVi": "Tôi đã quên cho mèo ăn rồi"},
        {"word": "拾う", "reading": "ひろう", "hanviet": "THẬP", "meaning": "Nhặt, lượm", "example": "道で財布を拾ったんです", "exampleVi": "Thật ra là tôi đã nhặt được cái ví trên đường"},
        {"word": "連絡する", "reading": "れんらくする", "hanviet": "LIÊN LẠC", "meaning": "Liên lạc", "example": "どこへ連絡したらいいですか", "exampleVi": "Tôi nên liên lạc vào đâu thì tốt"},
        {"word": "気分が良い", "reading": "きぶんがいい", "hanviet": "KHÍ PHÂN LƯƠNG", "meaning": "Cảm thấy khỏe, tinh thần tốt", "example": "散歩したので、気分が良いです", "exampleVi": "Vì đã đi dạo nên tôi cảm thấy rất khỏe"},
        {"word": "気分が悪い", "reading": "きぶんがわるい", "hanviet": "KHÍ PHÂN ÁC", "meaning": "Cảm thấy mệt, khó chịu trong người", "example": "気分が悪いんですが、帰ってもいいですか", "exampleVi": "Tôi thấy không khỏe, tôi về có được không"},
        {"word": "運動会", "reading": "うんどうかい", "hanviet": "VẬN ĐỘNG HỘI", "meaning": "Hội thi thể thao", "example": "来週、運動会があるんです", "exampleVi": "Tuần tới có hội thao đấy"},
        {"word": "盆踊り", "reading": "ぼんおどり", "hanviet": "BỒN DŨNG", "meaning": "Múa Bon (trong lễ hội Bon)", "example": "盆踊りに参加したことがありますか", "exampleVi": "Bạn đã từng tham gia múa Bon chưa"},
        {"word": "フリーマーケット", "reading": "フリーマーケット", "hanviet": "", "meaning": "Chợ trời, chợ đồ cũ", "example": "フリーマーケットへ行ってみませんか", "exampleVi": "Bạn có muốn thử đi chợ trời không"},
        {"word": "場所", "reading": "ばしょ", "hanviet": "TRƯỜNG SỞ", "meaning": "Địa điểm, nơi chốn", "example": "運動会の場所を教えていただけませんか", "exampleVi": "Bạn có thể chỉ giúp tôi địa điểm tổ chức hội thao không"},
        {"word": "ボランティア", "reading": "ボランティア", "hanviet": "", "meaning": "Tình nguyện viên", "example": "週末はボランティアに参加するつもりです", "exampleVi": "Cuối tuần tôi dự định tham gia tình nguyện"},
        {"word": "財布", "reading": "さいふ", "hanviet": "TÀI BỐ", "meaning": "Cái ví", "example": "どこで財布をなくしたか分かりません", "exampleVi": "Tôi không biết mình đã làm mất ví ở đâu"},
        {"word": "ごみ", "reading": "ごみ", "hanviet": "", "meaning": "Rác", "example": "どこにごみを出したらいいですか", "exampleVi": "Tôi nên đổ rác ở đâu thì tốt"},
        {"word": "国会議事堂", "reading": "こっかいぎじどう", "hanviet": "QUỐC HỘI NGHỊ SỰ ĐƯỜNG", "meaning": "Tòa nhà Quốc hội", "example": "国会議事堂を見学したいんですが", "exampleVi": "Tôi muốn đi tham quan tòa nhà Quốc hội"},
        {"word": "平日", "reading": "へいじつ", "hanviet": "BÌNH NHẬT", "meaning": "Ngày thường", "example": "平日は忙しいんですか", "exampleVi": "Ngày thường bạn có bận không"},
        {"word": "～弁", "reading": "べん", "hanviet": "BIỆN", "meaning": "Tiếng ~, giọng ~ (địa phương)", "example": "大阪弁は面白いと思います", "exampleVi": "Tôi nghĩ giọng Osaka rất thú vị"},
        {"word": "今度", "reading": "こんど", "hanviet": "KIM ĐỘ", "meaning": "Lần tới, lần này", "example": "今度の週末、空いていますか", "exampleVi": "Cuối tuần tới bạn có rảnh không"},
        {"word": "随分", "reading": "ずいぶん", "hanviet": "TÙY PHÂN", "meaning": "Khá, tương đối, rất", "example": "日本語が随分上手になりましたね", "exampleVi": "Tiếng Nhật của bạn đã tiến bộ khá nhiều nhỉ"},
        {"word": "直接", "reading": "ちょくせつ", "hanviet": "TRỰC TIẾP", "meaning": "Trực tiếp", "example": "直接先生に聞いたほうがいいですよ", "exampleVi": "Bạn nên hỏi trực tiếp thầy giáo thì tốt hơn đấy"},
        {"word": "いつでも", "reading": "いつでも", "hanviet": "", "meaning": "Lúc nào cũng, bất cứ khi nào", "example": "いつでも電話してください", "exampleVi": "Hãy gọi điện cho tôi bất cứ khi nào nhé"},
        {"word": "どこでも", "reading": "どこでも", "hanviet": "", "meaning": "Ở đâu cũng, bất cứ nơi nào", "example": "どこでも好きな場所へ行こう", "exampleVi": "Cùng đi tới bất kỳ nơi nào bạn thích nào"},
        {"word": "誰でも", "reading": "だれでも", "hanviet": "THÙY", "meaning": "Ai cũng, bất cứ ai", "example": "誰でもこのパソコンを使えます", "exampleVi": "Bất kỳ ai cũng có thể dùng chiếc máy tính này"},
        {"word": "何でも", "reading": "なんでも", "hanviet": "HÀ", "meaning": "Cái gì cũng, bất cứ thứ gì", "example": "分からないことは何でも聞いてください", "exampleVi": "Bất cứ điều gì không hiểu hãy cứ hỏi nhé"},
        {"word": "こんな～", "reading": "こんな", "hanviet": "", "meaning": "~ như thế này", "example": "こんな鞄が欲しいんです", "exampleVi": "Thật ra là tôi muốn một cái túi như thế này"},
        {"word": "そんな～", "reading": "そんな", "hanviet": "", "meaning": "~ như thế đó (gần người nghe)", "example": "そんな話は信じられません", "exampleVi": "Câu chuyện như thế đó thì tôi không thể tin được"},
        {"word": "あんな～", "reading": "あんな", "hanviet": "", "meaning": "~ như thế kia (xa cả người nói và người nghe)", "example": "あんな所にゴミを捨てないでください", "exampleVi": "Xin đừng vứt rác ở những nơi như thế kia"},
        {"word": "片付く", "reading": "かたづく", "hanviet": "PHIẾN PHÓ", "meaning": "Được dọn dẹp ngăn nắp, gọn gàng", "example": "部屋が綺麗に片付いていますね", "exampleVi": "Căn phòng đã được dọn dẹp thật ngăn nắp nhỉ"},
        {"word": "出す", "reading": "だす", "hanviet": "XUẤT", "meaning": "Đổ, để, vứt [rác]", "example": "どこにゴミを出したらいいですか", "exampleVi": "Tôi nên đổ rác ở đâu thì tốt nhỉ"},
        {"word": "燃えるごみ", "reading": "もえるごみ", "hanviet": "NHIÊN", "meaning": "Rác cháy được", "example": "今日は燃えるごみの日です", "exampleVi": "Hôm nay là ngày vứt rác cháy được"},
        {"word": "置き場", "reading": "おきば", "hanviet": "TRÌ TRƯỜNG", "meaning": "Nơi để, nơi đặt", "example": "自転車置き場はどこですか", "exampleVi": "Chỗ để xe đạp ở đâu vậy"},
        {"word": "横", "reading": "よこ", "hanviet": "HOÀNH", "meaning": "Bên cạnh, chiều ngang", "example": "ゴミ置き場はあのビルの横にあります", "exampleVi": "Nơi để rác nằm ở bên cạnh tòa nhà kia"},
        {"word": "瓶", "reading": "びん", "hanviet": "BÌNH", "meaning": "Cái chai", "example": "瓶はあっちに捨ててください", "exampleVi": "Hãy vứt chai lọ ở đằng kia nhé"},
        {"word": "缶", "reading": "かん", "hanviet": "PHẪU", "meaning": "Cái lon, hộp kim loại", "example": "缶や瓶は別の袋に入れてください", "exampleVi": "Hãy cho lon và chai vào túi khác nhé"},
        {"word": "ガス", "reading": "ガス", "hanviet": "", "meaning": "Ga, khí ga", "example": "ガス会社に連絡しなければなりません", "exampleVi": "Tôi phải liên lạc với công ty ga"},
        {"word": "～会社", "reading": "がいしゃ", "hanviet": "HỘI XÃ", "meaning": "Công ty ~", "example": "旅行会社で働いています", "exampleVi": "Tôi đang làm việc tại một công ty du lịch"},
        {"word": "宇宙", "reading": "うちゅう", "hanviet": "VŨ TRỤ", "meaning": "Vũ trụ", "example": "いつか宇宙へ行きたいと思っているんです", "exampleVi": "Thật ra là tôi đang định một lúc nào đó sẽ đi vào vũ trụ"},
        {"word": "～様", "reading": "さま", "hanviet": "DẠNG", "meaning": "Ông/Bà/Ngài ~ (kính ngữ)", "example": "田中様はいらっしゃいますか", "exampleVi": "Có ngài Tanaka ở đó không ạ"},
        {"word": "宇宙船", "reading": "うちゅうせん", "hanviet": "VŨ TRỤ THUYỀN", "meaning": "Tàu vũ trụ", "example": "宇宙船に乗るのが夢です", "exampleVi": "Được lên tàu vũ trụ là ước mơ của tôi"},
        {"word": "怖い", "reading": "こわい", "hanviet": "BỐ", "meaning": "Sợ, đáng sợ", "example": "宇宙へ行くのは怖いですか", "exampleVi": "Đi vào vũ trụ có đáng sợ không"},
        {"word": "宇宙ステーション", "reading": "うちゅうステーション", "hanviet": "VŨ TRỤ", "meaning": "Trạm vũ trụ", "example": "宇宙ステーションに半年います", "exampleVi": "Tôi sẽ ở trên trạm vũ trụ trong nửa năm"},
        {"word": "違う", "reading": "ちがう", "hanviet": "VI", "meaning": "Khác, sai, không phải", "example": "いいえ、それは違います", "exampleVi": "Không, cái đó không phải đâu"},
        {"word": "宇宙飛行士", "reading": "うちゅうひこうし", "hanviet": "VŨ TRỤ PHI HÀNH SĨ", "meaning": "Nhà du hành vũ trụ", "example": "子供の時、宇宙飛行士になりたかったんです", "exampleVi": "Thật ra hồi nhỏ tôi đã từng muốn trở thành nhà du hành vũ trụ"},
    ],
    27: [
        {"word": "飼う", "reading": "かう", "hanviet": "TỰ", "meaning": "Nuôi, chăn nuôi", "example": "ペットを飼いたいんですが、どこで買ったらいいですか", "exampleVi": "Tôi muốn nuôi thú cưng, tôi nên mua ở đâu thì tốt nhỉ"},
        {"word": "走る", "reading": "はしる", "hanviet": "TẨU", "meaning": "Chạy", "example": "10キロ走れるようになりました", "exampleVi": "Tôi đã có thể chạy được 10km rồi"},
        {"word": "見える", "reading": "みえる", "hanviet": "KIẾN", "meaning": "Có thể nhìn thấy, hiển thị", "example": "窓から海が見えるんです", "exampleVi": "Từ cửa sổ có thể nhìn thấy biển đấy"},
        {"word": "聞こえる", "reading": "きこえる", "hanviet": "VĂN", "meaning": "Có thể nghe thấy", "example": "隣の部屋から変な音が聞こえます", "exampleVi": "Có tiếng động lạ phát ra từ phòng bên cạnh"},
        {"word": "出来る", "reading": "できる", "hanviet": "XUẤT LAI", "meaning": "Được hoàn thành, được xây xong, có thể", "example": "駅の前に新しいマンションができました", "exampleVi": "Một căn chung cư mới đã được xây xong ở trước nhà ga"},
        {"word": "開く", "reading": "ひらく", "hanviet": "KHAI", "meaning": "Mở, tổ chức (lớp học, tiệc)", "example": "来月から料理教室を開くんです", "exampleVi": "Thật ra là từ tháng sau tôi sẽ mở lớp dạy nấu ăn"},
        {"word": "心配", "reading": "しんぱい", "hanviet": "TÂM PHỐI", "meaning": "Lo lắng", "example": "テストの結果が心配なんです", "exampleVi": "Thật ra là tôi đang lo lắng về kết quả bài kiểm tra"},
        {"word": "ペット", "reading": "ペット", "hanviet": "", "meaning": "Thú cưng, động vật nuôi", "example": "私のマンションはペットが飼えるんです", "exampleVi": "Chung cư của tôi có thể nuôi được thú cưng đấy"},
        {"word": "鳥", "reading": "とり", "hanviet": "ĐIỂU", "meaning": "Chim", "example": "鳥の声が聞こえますね", "exampleVi": "Nghe thấy tiếng chim hót nhỉ"},
        {"word": "声", "reading": "こえ", "hanviet": "THANH", "meaning": "Tiếng, giọng nói (người, động vật)", "example": "大きい声で話していただけませんか", "exampleVi": "Bạn có thể nói lớn tiếng hơn một chút được không"},
        {"word": "波", "reading": "なみ", "hanviet": "BA", "meaning": "Sóng, con sóng", "example": "波の音が聞こえて、気分が良いです", "exampleVi": "Nghe tiếng sóng biển thấy thật dễ chịu"},
        {"word": "花火", "reading": "はなび", "hanviet": "HOA HỎA", "meaning": "Pháo hoa", "example": "部屋から花火が見えるんですよ", "exampleVi": "Từ phòng có thể nhìn thấy pháo hoa đấy bạn"},
        {"word": "道具", "reading": "どうぐ", "hanviet": "ĐẠO CỤ", "meaning": "Dụng cụ, công cụ", "example": "どんな道具を使ったらいいですか", "exampleVi": "Tôi nên dùng loại dụng cụ như thế nào thì tốt"},
        {"word": "クリーニング", "reading": "クリーニング", "hanviet": "", "meaning": "Giặt ủi, giặt khô", "example": "このスーツをクリーニングに出したいんです", "exampleVi": "Thật ra là tôi muốn mang bộ com-lê này đi giặt ủi"},
        {"word": "家", "reading": "いえ", "hanviet": "GIA", "meaning": "Nhà, ngôi nhà", "example": "やっと自分の家ができました", "exampleVi": "Cuối cùng thì ngôi nhà của riêng tôi đã hoàn thành"},
        {"word": "マンション", "reading": "マンション", "hanviet": "", "meaning": "Chung cư, căn hộ cao cấp", "example": "新しいマンションを探しているんです", "exampleVi": "Thật ra là tôi đang tìm một căn chung cư mới"},
        {"word": "キッチン", "reading": "キッチン", "hanviet": "", "meaning": "Nhà bếp", "example": "このマンションはキッチンが広いですね", "exampleVi": "Căn chung cư này có nhà bếp rộng nhỉ"},
        {"word": "～教室", "reading": "きょうしつ", "hanviet": "GIÁO THẤT", "meaning": "Lớp học ~, phòng học ~", "example": "日本語教室に通っているんです", "exampleVi": "Thật ra là tôi đang đi học ở lớp tiếng Nhật"},
        {"word": "パーティールーム", "reading": "パーティールーム", "hanviet": "", "meaning": "Phòng tiệc", "example": "このマンションはパーティールームが使えるんです", "exampleVi": "Căn chung cư này có thể sử dụng được cả phòng tiệc đấy"},
        {"word": "方", "reading": "かた", "hanviet": "PHƯƠNG", "meaning": "Vị, người (kính ngữ)", "example": "あちらの方はどなたですか", "exampleVi": "Vị ở đằng kia là ai vậy ạ"},
        {"word": "〜後", "reading": "ご", "hanviet": "HẬU", "meaning": "~ sau (thời gian)", "example": "仕事の後に、友達と会う予定です", "exampleVi": "Theo kế hoạch thì sau khi xong việc tôi sẽ gặp bạn"},
        {"word": "～しか", "reading": "しか", "hanviet": "", "meaning": "Chỉ (đi với phủ định)", "example": "財布に千円しか入っていないんです", "exampleVi": "Trong ví thật ra chỉ còn có 1000 yên thôi"},
        {"word": "他の", "reading": "ほかの", "hanviet": "THA", "meaning": "Khác", "example": "他の場所を探さなければなりません", "exampleVi": "Tôi phải đi tìm một địa điểm khác"},
        {"word": "はっきり", "reading": "はっきり", "hanviet": "", "meaning": "Rõ ràng", "example": "今日は天気がいいので、山がはっきり見えます", "exampleVi": "Vì hôm nay trời đẹp nên có thể nhìn thấy núi rất rõ"},
        {"word": "家具", "reading": "かぐ", "hanviet": "GIA CỤ", "meaning": "Đồ gỗ, nội thất", "example": "この家具はデザインが素晴らしいんです", "exampleVi": "Bộ nội thất này thật ra có thiết kế rất tuyệt vời"},
        {"word": "本棚", "reading": "ほんだな", "hanviet": "BẢN BẰNG", "meaning": "Kệ sách, giá sách", "example": "本棚を自分で作りたいんですが、どうしたらいいですか", "exampleVi": "Tôi muốn tự mình làm kệ sách, tôi nên làm thế nào thì tốt nhỉ"},
        {"word": "いつか", "reading": "いつか", "hanviet": "", "meaning": "Một ngày nào đó", "example": "いつか自分の家を建てたいと思っているんです", "exampleVi": "Thật ra là tôi đang dự định một ngày nào đó sẽ xây nhà riêng"},
        {"word": "建てる", "reading": "たてる", "hanviet": "KIẾN", "meaning": "Xây dựng", "example": "広い家を建てるために、貯金しているんです", "exampleVi": "Thật ra là tôi đang tiết kiệm tiền để xây một ngôi nhà rộng"},
        {"word": "素晴らしい", "reading": "すばらしい", "hanviet": "TỐ TÌNH", "meaning": "Tuyệt vời", "example": "昨日の花火は本当に素晴らしかったですね", "exampleVi": "Pháo hoa ngày hôm qua thực sự rất tuyệt vời nhỉ"},
        {"word": "子供達", "reading": "こどもたち", "hanviet": "TỬ CUNG ĐẠT", "meaning": "Trẻ em, bọn trẻ", "example": "子供達が公園で自由に遊んでいます", "exampleVi": "Bọn trẻ đang vui chơi tự do ở công viên"},
        {"word": "大好き", "reading": "だいすき", "hanviet": "ĐẠI HẢO", "meaning": "Rất thích", "example": "日本のアニメが大好きなんです", "exampleVi": "Thật ra là tôi cực kỳ thích phim hoạt hình Nhật Bản"},
        {"word": "主人公", "reading": "しゅじんこう", "hanviet": "CHỦ NHÂN CÔNG", "meaning": "Nhân vật chính", "example": "この漫画の主人公は不思議な力を持っているんです", "exampleVi": "Nhân vật chính của cuốn truyện tranh này có một sức mạnh kỳ bí đấy"},
        {"word": "形", "reading": "かたち", "hanviet": "HÌNH", "meaning": "Hình dạng", "example": "珍しい形の家具を探しているんです", "exampleVi": "Thật ra là tôi đang tìm món đồ nội thất có hình dáng lạ"},
        {"word": "不思議", "reading": "ふしぎ", "hanviet": "BẤT TƯ NGHỊ", "meaning": "Kỳ lạ, huyền bí", "example": "あの山には不思議な話があるんです", "exampleVi": "Ở ngọn núi kia thật ra có một câu chuyện kỳ bí"},
        {"word": "ポケット", "reading": "ポケット", "hanviet": "", "meaning": "Túi (quần áo)", "example": "ポケットに何が入っているんですか", "exampleVi": "Có cái gì đang ở trong túi của bạn vậy nhỉ"},
        {"word": "例えば", "reading": "たとえば", "hanviet": "LỆ", "meaning": "Ví dụ", "example": "例えば、どんなスポーツが好きですか", "exampleVi": "Ví dụ như, bạn thích môn thể thao nào"},
        {"word": "付ける", "reading": "つける", "hanviet": "PHÓ", "meaning": "Lắp ghép, gắn vào", "example": "自分でボタンを付けることができます", "exampleVi": "Tôi có thể tự mình đơm (gắn) cúc áo"},
        {"word": "自由に", "reading": "じゆうに", "hanviet": "TỰ DO", "meaning": "Tự do", "example": "いつでも自由にこの部屋を使ってください", "exampleVi": "Hãy cứ sử dụng căn phòng này một cách tự do bất cứ lúc nào nhé"},
        {"word": "空", "reading": "そら", "hanviet": "KHÔNG", "meaning": "Bầu trời", "example": "空がはっきり見えて、素晴らしいですね", "exampleVi": "Bầu trời có thể nhìn thấy rất rõ, thật tuyệt vời nhỉ"},
        {"word": "飛ぶ", "reading": "とぶ", "hanviet": "PHI", "meaning": "Bay", "example": "鳥のように空を飛びたいと思っているんです", "exampleVi": "Thật ra là tôi đang mơ ước được bay lượn trên trời như loài chim"},
        {"word": "昔", "reading": "むかし", "hanviet": "TÍCH", "meaning": "Ngày xưa", "example": "昔、この場所にお寺があったんです", "exampleVi": "Ngày xưa, ở địa điểm này thật ra đã từng có một ngôi chùa"},
        {"word": "自分", "reading": "じぶん", "hanviet": "TỰ PHÂN", "meaning": "Tự mình", "example": "自分の家を建てたいと思っているんです", "exampleVi": "Thật ra là tôi đang dự định muốn xây một ngôi nhà của riêng mình"},
        {"word": "将来", "reading": "しょうらい", "hanviet": "TƯƠNG LAI", "meaning": "Tương lai (gần)", "example": "将来、宇宙飛行士になりたいんです", "exampleVi": "Trong tương lai, thật ra là tôi muốn trở thành nhà du hành vũ trụ"},
    ],
    28: [
        {"word": "売れる", "reading": "うれる", "hanviet": "MẠI", "meaning": "Bán chạy, được bán", "example": "このパンは美味しいので、よく売れるんです", "exampleVi": "Chiếc bánh mì này vì ngon nên bán rất chạy đấy"},
        {"word": "踊る", "reading": "おどる", "hanviet": "DŨNG", "meaning": "Nhảy, khiêu vũ", "example": "音楽を聞きながら、踊るのが好きです", "exampleVi": "Tôi thích vừa nghe nhạc vừa nhảy"},
        {"word": "噛む", "reading": "かむ", "hanviet": "GIẢO", "meaning": "Nhai, cắn", "example": "よく噛んで食べないと、お腹が痛くなりますよ", "exampleVi": "Nếu không nhai kỹ mà ăn thì sẽ bị đau bụng đấy nhé"},
        {"word": "選ぶ", "reading": "えらぶ", "hanviet": "TUYỂN", "meaning": "Chọn, lựa chọn", "example": "どれを選んだらいいか、教えていただけませんか", "exampleVi": "Bạn có thể chỉ giúp tôi xem nên chọn cái nào thì tốt không"},
        {"word": "通う", "reading": "かよう", "hanviet": "THÔNG", "meaning": "Đi học, đi làm, đi lại thường xuyên", "example": "私はハノイの大学に通っています", "exampleVi": "Tôi đang đi học tại một trường đại học ở Hà Nội"},
        {"word": "メモする", "reading": "メモする", "hanviet": "", "meaning": "Ghi chép, ghi lại", "example": "忘れないように、メモするようにしてください", "exampleVi": "Hãy chú ý ghi chép lại để không bị quên nhé"},
        {"word": "真面目", "reading": "まじめ", "hanviet": "CHÂN DIỆN MỤC", "meaning": "Nghiêm túc, chăm chỉ", "example": "彼は真面目だし、親切なので、人気があります", "exampleVi": "Anh ấy vừa nghiêm túc lại vừa tử tế nên rất được yêu thích"},
        {"word": "熱心", "reading": "ねっしん", "hanviet": "NHIỆT TÂM", "meaning": "Nhiệt tình, hết lòng", "example": "田中さんは熱心に日本語を勉強しているんです", "exampleVi": "Thật ra là anh Tanaka đang học tiếng Nhật rất nhiệt huyết"},
        {"word": "偉い", "reading": "えらい", "hanviet": "VĨ", "meaning": "Vĩ đại, đáng kính, đáng khâm phục", "example": "自分で料理を作る人は、偉いと思います", "exampleVi": "Tôi nghĩ những người tự mình nấu ăn thật là đáng khâm phục"},
        {"word": "丁度いい", "reading": "ちょうどいい", "hanviet": "ĐINH ĐỘ", "meaning": "Vừa đúng, vừa đủ", "example": "この靴は私にサイズが丁度いいです", "exampleVi": "Đôi giày này có kích cỡ vừa vặn với tôi"},
        {"word": "景色", "reading": "けしき", "hanviet": "CẢNH SẮC", "meaning": "Phong cảnh", "example": "ここから海の景色がはっきり見えるんですよ", "exampleVi": "Từ đây có thể nhìn thấy rõ phong cảnh biển đấy bạn"},
        {"word": "美容院", "reading": "びよういん", "hanviet": "MĨ DUNG VIỆN", "meaning": "Hiệu làm đẹp, thẩm mỹ viện", "example": "明日は美容院へ髪を切りに行くつもりです", "exampleVi": "Ngày mai tôi định đi hiệu làm đẹp để cắt tóc"},
        {"word": "台所", "reading": "だいどころ", "hanviet": "ĐÀI SỞ", "meaning": "Nhà bếp", "example": "台所に美味しそうなケーキが置いてあります", "exampleVi": "Trong bếp có đặt một chiếc bánh kem trông rất ngon"},
        {"word": "経験", "reading": "けいけん", "hanviet": "KINH NGHIỆM", "meaning": "Kinh nghiệm", "example": "日本で働いた経験がありますか", "exampleVi": "Bạn đã từng có kinh nghiệm làm việc ở Nhật Bản chưa"},
        {"word": "力", "reading": "ちから", "hanviet": "LỰC", "meaning": "Sức lực, năng lực", "example": "このロボットは、力が強いし、動くのも速いです", "exampleVi": "Con rô bốt này vừa khỏe lại vừa di chuyển nhanh"},
        {"word": "人気", "reading": "にんき", "hanviet": "NHÂN KHÍ", "meaning": "Sự yêu thích, hâm mộ", "example": "あのアニメは、世界中で人気があるそうですよ", "exampleVi": "Nghe nói bộ phim hoạt hình kia đang được yêu thích trên toàn thế giới đấy"},
        {"word": "形", "reading": "かたち", "hanviet": "HÌNH", "meaning": "Hình dáng, hình dạng", "example": "珍しい形のカメラを探しているんです", "exampleVi": "Thật ra là tôi đang tìm một chiếc máy ảnh có hình dáng lạ"},
        {"word": "色", "reading": "いろ", "hanviet": "SẮC", "meaning": "Màu sắc", "example": "君のネクタイは色が綺麗だし、丁度いいですね", "exampleVi": "Cà vạt của cậu màu sắc đẹp mà lại rất vừa vặn nữa"},
        {"word": "味", "reading": "あじ", "hanviet": "VỊ", "meaning": "Vị, hương vị", "example": "この料理は、味が薄いかもしれません", "exampleVi": "Món ăn này có lẽ là vị hơi nhạt"},
        {"word": "ガム", "reading": "ガム", "hanviet": "", "meaning": "Kẹo cao su", "example": "歩きながら、ガムを噛まないでください", "exampleVi": "Xin đừng vừa đi vừa nhai kẹo cao su"},
        {"word": "品物", "reading": "しなもの", "hanviet": "PHẨM VẬT", "meaning": "Hàng hóa, mặt hàng", "example": "デパートには、いい品物がたくさんあります", "exampleVi": "Ở trung tâm thương mại có rất nhiều mặt hàng tốt"},
        {"word": "値段", "reading": "ねだん", "hanviet": "TRỊ ĐOẠN", "meaning": "Giá cả", "example": "品物はいいですが、値段がちょっと高すぎます", "exampleVi": "Hàng thì tốt đấy nhưng giá hơi cao quá"},
        {"word": "給料", "reading": "きゅうりょう", "hanviet": "CẤP LIỆU", "meaning": "Tiền lương", "example": "給料をもらったら、新しい服を買う予定です", "exampleVi": "Sau khi nhận lương, tôi dự định sẽ mua quần áo mới"},
        {"word": "ボーナス", "reading": "ボーナス", "hanviet": "", "meaning": "Tiền thưởng, bonus", "example": "ボーナスがたくさん出るといいですね", "exampleVi": "Nếu được thưởng nhiều thì tốt quá nhỉ"},
        {"word": "ゲーム", "reading": "ゲーム", "hanviet": "", "meaning": "Trò chơi, game", "example": "夜遅くまで、ゲームをしないほうがいいですよ", "exampleVi": "Bạn không nên chơi game cho đến tận đêm muộn đâu"},
        {"word": "番組", "reading": "ばんぐみ", "hanviet": "PHIÊN TỔ", "meaning": "Chương trình (phát thanh, truyền hình)", "example": "この番組は面白いし、役に立つんです", "exampleVi": "Chương trình này vừa thú vị lại vừa có ích nữa"},
        {"word": "ドラマ", "reading": "ドラマ", "hanviet": "", "meaning": "Kịch, phim truyền hình", "example": "日本のドラマを見ながら、日本語を勉強しています", "exampleVi": "Tôi đang vừa xem phim truyền hình Nhật vừa học tiếng Nhật"},
        {"word": "歌手", "reading": "かしゅ", "hanviet": "CA THỦ", "meaning": "Ca sĩ", "example": "彼女は歌も上手だし、将来有名な歌手になるでしょう", "exampleVi": "Cô ấy hát cũng giỏi nên tương lai chắc sẽ trở thành ca sĩ nổi tiếng thôi"},
        {"word": "小説", "reading": "しょうせつ", "hanviet": "TIỂU THUYẾT", "meaning": "Tiểu thuyết", "example": "暇な時、日本の小説を読んでいるんです", "exampleVi": "Lúc rảnh rỗi tôi thường đọc tiểu thuyết Nhật Bản đấy"},
        {"word": "小説家", "reading": "しょうせつか", "hanviet": "TIỂU THUYẾT GIA", "meaning": "Tiểu thuyết gia, nhà văn", "example": "私の夢は小説家になることなんです", "exampleVi": "Ước mơ của tôi là trở thành nhà văn đấy"},
        {"word": "～家", "reading": "か", "hanviet": "GIA", "meaning": "Nhà ~, chuyên gia về ~", "example": "有名な政治家とお会いしたことがあるんです", "exampleVi": "Thực ra là tôi đã từng được gặp một nhà chính trị nổi tiếng"},
        {"word": "～機", "reading": "き", "hanviet": "CƠ", "meaning": "Máy ~, máy móc ~", "example": "このコピー機は使いやすくて、便利なんです", "exampleVi": "Cái máy photocopy này dễ dùng mà lại tiện lợi nữa"},
        {"word": "息子", "reading": "むすこ", "hanviet": "TỨC TỬ", "meaning": "Con trai (của mình)", "example": "息子は今、ハノイの大学に通っているんです", "exampleVi": "Con trai tôi hiện đang đi học đại học ở Hà Nội đấy"},
        {"word": "息子さん", "reading": "むすこさん", "hanviet": "TỨC TỬ", "meaning": "Con trai (của người khác)", "example": "息子さんは背も高いし、真面目そうですね", "exampleVi": "Con trai anh vừa cao lại trông có vẻ nghiêm túc nhỉ"},
        {"word": "娘", "reading": "むすめ", "hanviet": "NƯƠNG", "meaning": "Con gái (của mình)", "example": "娘はピアノを弾きながら、歌うのが好きなんです", "exampleVi": "Con gái tôi thích vừa đánh đàn piano vừa hát đấy"},
        {"word": "娘さん", "reading": "むすめさん", "hanviet": "NƯƠNG", "meaning": "Con gái (của người khác)", "example": "娘さんはもうすぐ結婚なさるそうですね", "exampleVi": "Nghe nói con gái anh sắp kết hôn phải không ạ"},
        {"word": "自分", "reading": "じぶん", "hanviet": "TỰ PHÂN", "meaning": "Bản thân, mình", "example": "自分のことは自分でしなければなりません", "exampleVi": "Việc của bản thân thì phải tự mình làm thôi"},
        {"word": "将来", "reading": "しょうらい", "hanviet": "TƯƠNG LAI", "meaning": "Tương lai", "example": "将来について、よく考えておいたほうがいいですよ", "exampleVi": "Bạn nên suy nghĩ kỹ sẵn về tương lai của mình đi nhé"},
        {"word": "暫く", "reading": "しばらく", "hanviet": "TẠM", "meaning": "Một lúc, một lát, một thời gian", "example": "すみませんが、しばらくここで待っていただけませんか", "exampleVi": "Xin lỗi, anh có thể đợi ở đây một lát được không ạ"},
        {"word": "大抵", "reading": "たいてい", "hanviet": "ĐẠI ĐỂ", "meaning": "Thông thường, đại để", "example": "週末は大抵家で本を読んでいるんです", "exampleVi": "Cuối tuần thì thông thường tôi hay ở nhà đọc sách"},
        {"word": "それに", "reading": "それに", "hanviet": "", "meaning": "Hơn nữa, thêm vào đó", "example": "この店は安いし、それに味もいいんです", "exampleVi": "Quán này vừa rẻ, hơn nữa vị lại còn ngon nữa"},
        {"word": "それで", "reading": "それで", "hanviet": "", "meaning": "Thế thì, vì thế nên", "example": "道が混んでいたんです。それで遅れました", "exampleVi": "Thực ra là đường đã bị tắc. Thế nên tôi mới bị muộn"},
        {"word": "[ちょっと]お願いがあるんですが", "reading": "おねがいがあるんですが", "hanviet": "NGUYỆN", "meaning": "Tôi có chút việc muốn nhờ", "example": "ちょっとお願いがあるんですが、これを見ていただけませんか", "exampleVi": "Tôi có chút việc muốn nhờ, anh xem giúp tôi cái này được không"},
        {"word": "実は", "reading": "じつは", "hanviet": "THỰC", "meaning": "Thực ra là", "example": "実は、来月会社を辞めるつもりなんです", "exampleVi": "Thực ra là tháng sau tôi định nghỉ việc ở công ty"},
        {"word": "会話", "reading": "かいわ", "hanviet": "HỘI THOẠI", "meaning": "Hội thoại", "example": "毎日CDを聞きながら、会話を練習しているんです", "exampleVi": "Mỗi ngày tôi đều vừa nghe CD vừa luyện hội thoại đấy"},
        {"word": "うーん", "reading": "うーん", "hanviet": "", "meaning": "Ừm, hừm (đang suy nghĩ)", "example": "うーん、それはちょっと難しいですね", "exampleVi": "Ừm, cái đó thì hơi khó nhỉ"},
        {"word": "お知らせ", "reading": "おしらせ", "hanviet": "TRI", "meaning": "Thông báo", "example": "イベントのお知らせを読んだんですか", "exampleVi": "Bạn đã đọc thông báo về sự kiện chưa"},
        {"word": "参加する", "reading": "さんかする", "hanviet": "THAM GIA", "meaning": "Tham gia", "example": "ボランティアに参加するつもりなんです", "exampleVi": "Tôi đang có dự định tham gia hoạt động tình nguyện"},
        {"word": "日にち", "reading": "ひにち", "hanviet": "NHẬT", "meaning": "Ngày, ngày giờ", "example": "日にちが決まったら、教えていただけませんか", "exampleVi": "Khi nào quyết định được ngày thì bạn có thể cho tôi biết được không"},
        {"word": "土", "reading": "ど", "hanviet": "THỔ", "meaning": "Thứ bảy", "example": "土曜日なら、都合がいいんです", "exampleVi": "Nếu là thứ Bảy thì thật ra là tôi thấy rất tiện"},
        {"word": "体育館", "reading": "たいいくかん", "hanviet": "THỂ DỤC QUÁN", "meaning": "Nhà tập, nhà thi đấu thể thao", "example": "体育館でバスケットボールをしているんです", "exampleVi": "Thật ra là (họ) đang chơi bóng rổ ở nhà thi đấu"},
        {"word": "無料", "reading": "むりょう", "hanviet": "VÔ LIỆU", "meaning": "Miễn phí", "example": "このイベントは無料だし、面白いですよ", "exampleVi": "Sự kiện này vừa miễn phí lại vừa thú vị đấy"},
        {"word": "誘う", "reading": "さそう", "hanviet": "DỤ", "meaning": "Mời, rủ rê", "example": "友達を誘って、一緒に行きませんか", "exampleVi": "Chúng mình rủ bạn bè rồi cùng đi không"},
        {"word": "イベント", "reading": "イベント", "hanviet": "", "meaning": "Sự kiện", "example": "日本には色々なイベントがあるそうですよ", "exampleVi": "Nghe nói ở Nhật Bản có rất nhiều sự kiện đa dạng đấy"},
    ],
    29: [
        {"word": "開く", "reading": "あく", "hanviet": "KHAI", "meaning": "Mở [cửa đang mở]", "example": "教室のドアが開いていますね", "exampleVi": "Cửa phòng học đang mở nhỉ"},
        {"word": "閉まる", "reading": "しまる", "hanviet": "BẾ", "meaning": "Đóng [cửa đang đóng]", "example": "窓が閉まっていますから、暑いんです", "exampleVi": "Vì cửa sổ đang đóng nên thật là nóng"},
        {"word": "点く", "reading": "つく", "hanviet": "ĐIỂM", "meaning": "Sáng [điện đang sáng]", "example": "電気が点いていますよ", "exampleVi": "Điện đang sáng đấy bạn"},
        {"word": "消える", "reading": "きえる", "hanviet": "TIÊU", "meaning": "Tắt [điện đang tắt]", "example": "テレビが消えていますね。誰もいないんですか", "exampleVi": "Tivi đang tắt nhỉ. Không có ai ở đây à"},
        {"word": "壊れる", "reading": "こわれる", "hanviet": "HOẠI", "meaning": "Hỏng [đang bị hỏng]", "example": "パソコンが壊れてしまったんです", "exampleVi": "Thật ra là máy tính của tôi đã bị hỏng mất rồi"},
        {"word": "割れる", "reading": "われる", "hanviet": "CÁT", "meaning": "Vỡ [đang bị vỡ]", "example": "コップが割れていますから、気を付けてください", "exampleVi": "Cái cốc đang bị vỡ đấy nên hãy cẩn thận nhé"},
        {"word": "折れる", "reading": "おれる", "hanviet": "CHIẾT", "meaning": "Gãy [đang bị gãy]", "example": "強い風で木が折れています", "exampleVi": "Cái cây đang bị gãy do gió mạnh"},
        {"word": "破れる", "reading": "やぶれる", "hanviet": "PHÁ", "meaning": "Rách [đang bị rách]", "example": "この袋は破れていますよ", "exampleVi": "Cái túi này đang bị rách đấy"},
        {"word": "汚れる", "reading": "よごれる", "hanviet": "Ô", "meaning": "Bẩn [đang bị bẩn]", "example": "白いシャツが汚れてしまいました", "exampleVi": "Cái áo sơ mi trắng đã bị vấy bẩn mất rồi"},
        {"word": "付く", "reading": "つく", "hanviet": "PHÓ", "meaning": "Có gắn, kèm theo", "example": "この鞄には大きなポケットが付いています", "exampleVi": "Trên chiếc cặp này có gắn một cái túi lớn"},
        {"word": "外れる", "reading": "はずれる", "hanviet": "NGOẠI", "meaning": "Tuột, bung [đang bị bung]", "example": "ボタンが外れていますよ", "exampleVi": "Cái cúc áo đang bị bung kìa"},
        {"word": "止まる", "reading": "とまる", "hanviet": "CHỈ", "meaning": "Dừng [đang dừng]", "example": "あそこに車が止まっていますね", "exampleVi": "Có chiếc xe hơi đang dừng ở đằng kia nhỉ"},
        {"word": "間違える", "reading": "まちがえる", "hanviet": "GIAN VI", "meaning": "Nhầm, sai", "example": "電車を間違えてしまったんです", "exampleVi": "Thật ra là tôi đã đi nhầm chuyến tàu mất rồi"},
        {"word": "落とす", "reading": "おとす", "hanviet": "LẠC", "meaning": "Đánh rơi", "example": "どこかで財布を落としてしまいました", "exampleVi": "Tôi đã làm rơi mất cái ví ở đâu đó rồi"},
        {"word": "掛かる", "reading": "かかる", "hanviet": "QUẢI", "meaning": "Khóa [đang được khóa]", "example": "鍵が掛かっていますから、入れません", "exampleVi": "Vì cửa đang khóa nên không thể vào được"},
        {"word": "拭く", "reading": "ふく", "hanviet": "THỨC", "meaning": "Lau, chùi", "example": "お客様が来る前に、テーブルを拭いておきます", "exampleVi": "Tôi sẽ lau bàn sẵn trước khi khách đến"},
        {"word": "取り替える", "reading": "とりかえる", "hanviet": "THỦ THẾ", "meaning": "Thay, trao đổi", "example": "電池を取り替えたほうがいいですよ", "exampleVi": "Bạn nên thay pin đi thì tốt hơn đấy"},
        {"word": "片付ける", "reading": "かたづける", "hanviet": "PHIẾN PHÓ", "meaning": "Dọn dẹp", "example": "もう部屋を片付けてしまいました", "exampleVi": "Tôi đã dọn dẹp xong căn phòng rồi"},
        {"word": "皿", "reading": "さら", "hanviet": "MÃNH", "meaning": "Cái đĩa", "example": "割れた皿があそこに置いてあります", "exampleVi": "Những chiếc đĩa bị vỡ đang được đặt ở đằng kia"},
        {"word": "茶碗", "reading": "ちゃわん", "hanviet": "TRÀ OẢN", "meaning": "Cái bát, chén", "example": "茶碗をもう洗ってしまいました", "exampleVi": "Tôi đã giặt (rửa) xong hết bát chén rồi"},
        {"word": "コップ", "reading": "コップ", "hanviet": "", "meaning": "Cái cốc, ly", "example": "コップを割ってしまったんです。すみません", "exampleVi": "Thật ra là tôi đã lỡ làm vỡ cái cốc mất rồi. Tôi xin lỗi"},
        {"word": "ガラス", "reading": "ガラス", "hanviet": "", "meaning": "Thủy tinh, kính", "example": "強い風で窓ガラスが割れてしまったんです", "exampleVi": "Do gió mạnh nên kính cửa sổ đã bị vỡ mất rồi"},
        {"word": "袋", "reading": "ふくろ", "hanviet": "ĐẠI", "meaning": "Cái túi", "example": "この袋は破れていますから、取り替えていただけませんか", "exampleVi": "Cái túi này bị rách rồi, bạn có thể đổi cái khác giúp tôi được không"},
        {"word": "書類", "reading": "しょるい", "hanviet": "THƯ LOẠI", "meaning": "Giấy tờ, tài liệu", "example": "大切な書類が机の上に置いてあります", "exampleVi": "Tài liệu quan trọng đang được đặt ở trên bàn"},
        {"word": "枝", "reading": "えだ", "hanviet": "CHI", "meaning": "Cành cây", "example": "あそこの木は枝が折れていますね", "exampleVi": "Cái cây đằng kia cành bị gãy rồi nhỉ"},
        {"word": "駅員", "reading": "えきいん", "hanviet": "DỊCH VIÊN", "meaning": "Nhân viên nhà ga", "example": "忘れ物をしたので、駅員に聞いているんです", "exampleVi": "Vì để quên đồ nên tôi đang hỏi nhân viên nhà ga"},
        {"word": "交番", "reading": "こうばん", "hanviet": "GIAO PHIÊN", "meaning": "Đồn cảnh sát, bốt cảnh sát", "example": "財布をなくしたときは、交番へ行ったらいいですよ", "exampleVi": "Khi mất ví thì bạn nên đến đồn cảnh sát"},
        {"word": "スピーチ", "reading": "スピーチ", "hanviet": "", "meaning": "Bài diễn văn, phát biểu", "example": "明日スピーチをしなければならないので、練習しているんです", "exampleVi": "Vì mai phải phát biểu nên tôi đang luyện tập đây"},
        {"word": "返事", "reading": "へんじ", "hanviet": "PHẢN SỰ", "meaning": "Trả lời, hồi âm", "example": "メールを送りましたが、まだ返事が来ないんです", "exampleVi": "Tôi đã gửi mail rồi mà vẫn chưa thấy hồi âm"},
        {"word": "お先にどうぞ", "reading": "おさきにどうぞ", "hanviet": "TIÊN", "meaning": "Xin mời anh/chị đi trước", "example": "急いでいますか。お先にどうぞ", "exampleVi": "Bạn đang vội à. Mời bạn đi trước"},
        {"word": "今の電車", "reading": "いまのでんしゃ", "hanviet": "KIM ĐIỆN XA", "meaning": "Đoàn tàu vừa rồi", "example": "今の電車に忘れ物をしてしまったんです", "exampleVi": "Tôi lỡ quên đồ trên đoàn tàu vừa rồi mất rồi"},
        {"word": "忘れ物", "reading": "わすれもの", "hanviet": "VONG VẬT", "meaning": "Vật để quên", "example": "忘れ物がないか、確認してください", "exampleVi": "Hãy kiểm tra xem có để quên đồ gì không nhé"},
        {"word": "このくらい", "reading": "このくらい", "hanviet": "", "meaning": "Khoảng ngần này, cỡ này", "example": "このくらいのサイズの袋を探しているんです", "exampleVi": "Thật ra là tôi đang tìm một cái túi cỡ khoảng ngần này"},
        {"word": "～側", "reading": "がわ", "hanviet": "TRẮC", "meaning": "Phía ~, bên ~", "example": "道路の右側を歩かないでください", "exampleVi": "Đừng đi bộ bên phía tay phải của con đường nhé"},
        {"word": "ポケット", "reading": "ポケット", "hanviet": "", "meaning": "Túi (áo, quần)", "example": "上着のポケットにハンカチが入れてあります", "exampleVi": "Một chiếc khăn tay đã được để sẵn trong túi áo khoác"},
        {"word": "～辺", "reading": "へん", "hanviet": "BIÊN", "meaning": "Xung quanh ~, vùng ~", "example": "この辺に交番があるか、教えていただけませんか", "exampleVi": "Bạn có thể cho tôi biết xung quanh đây có đồn cảnh sát nào không"},
        {"word": "覚えていません", "reading": "おぼえていません", "hanviet": "GIÁC", "meaning": "Tôi không nhớ", "example": "どこに置いたか、はっきり覚えていません", "exampleVi": "Tôi không nhớ rõ mình đã để nó ở đâu nữa"},
        {"word": "網棚", "reading": "あみだな", "hanviet": "VÕNG BẰNG", "meaning": "Giá hành lý (trên tàu)", "example": "網棚の上に鞄が置いてあります", "exampleVi": "Cái cặp đang được đặt ở trên giá hành lý"},
        {"word": "確か", "reading": "たしか", "hanviet": "XÁC", "meaning": "Nếu không lầm thì, chắc là", "example": "確かあの辺に交番があったと思います", "exampleVi": "Tôi nghĩ chắc là ở quanh khu đó đã từng có đồn cảnh sát"},
        {"word": "[ああ、]よかった", "reading": "よかった", "hanviet": "", "meaning": "Ồ, may quá", "example": "忘れ物が見つかったんですか。ああ、よかった", "exampleVi": "Bạn đã tìm thấy đồ để quên rồi à. Ôi, may quá"},
        {"word": "新宿", "reading": "しんじゅく", "hanviet": "TÂN TÚC", "meaning": "Shinjuku (địa điểm ở Tokyo)", "example": "新宿駅で別の電車に乗り換えるんです", "exampleVi": "Tôi sẽ chuyển sang một đoàn tàu khác tại ga Shinjuku đấy"},
        {"word": "地震", "reading": "じしん", "hanviet": "ĐỊA CHẤN", "meaning": "Động đất", "example": "大きな地震でビルが倒れてしまいました", "exampleVi": "Tòa nhà đã bị đổ do một trận động đất lớn"},
        {"word": "壁", "reading": "かべ", "hanviet": "BÍCH", "meaning": "Bức tường", "example": "壁に綺麗なカレンダーが掛けてあります", "exampleVi": "Một tờ lịch đẹp đang được treo trên tường"},
        {"word": "針", "reading": "はり", "hanviet": "CHÂM", "meaning": "Kim (đồng hồ, khâu)", "example": "時計の針が止まっていますね。故障ですか", "exampleVi": "Kim đồng hồ đang dừng kìa. Bị hỏng à"},
        {"word": "指す", "reading": "さす", "hanviet": "CHỈ", "meaning": "Chỉ, hướng về", "example": "時計の針が12時を指しています", "exampleVi": "Kim đồng hồ đang chỉ 12 giờ"},
        {"word": "駅前", "reading": "えきまえ", "hanviet": "DỊCH TIỀN", "meaning": "Khu vực trước nhà ga", "example": "駅前に新しいマンションができたんです", "exampleVi": "Thật ra là khu trước nhà ga vừa có một căn chung cư mới hoàn thành"},
        {"word": "倒れる", "reading": "たおれる", "hanviet": "ĐẢO", "meaning": "Đổ, ngã, sụp đổ", "example": "地震で木が倒れてしまったんです", "exampleVi": "Cái cây đã bị đổ do động đất mất rồi"},
        {"word": "西", "reading": "にし", "hanviet": "TÂY", "meaning": "Tây, phía tây", "example": "西の方に大きなビルが見えます", "exampleVi": "Có thể nhìn thấy tòa nhà lớn ở phía Tây"},
        {"word": "～の方", "reading": "のほう", "hanviet": "PHƯƠNG", "meaning": "Phía ~, hướng ~", "example": "あちらの方へ行ってみませんか", "exampleVi": "Bạn có muốn thử đi về hướng kia không"},
        {"word": "燃える", "reading": "もえる", "hanviet": "NHIÊN", "meaning": "Cháy", "example": "火事で古い家が燃えてしまいました", "exampleVi": "Ngôi nhà cũ đã bị cháy rụi do hỏa hoạn mất rồi"},
        {"word": "レポーター", "reading": "レポーター", "hanviet": "", "meaning": "Phóng viên", "example": "レポーターが地震について説明しています", "exampleVi": "Phóng viên đang giải thích về trận động đất"},
    ],
    30: [
        {"word": "貼る", "reading": "はる", "hanviet": "THIẾP", "meaning": "Dán, dán lên", "example": "壁にお知らせが貼ってあります", "exampleVi": "Thông báo đang được dán trên tường"},
        {"word": "掛ける", "reading": "かける", "hanviet": "QUẢI", "meaning": "Treo", "example": "カレンダーはあそこに掛けておいてください", "exampleVi": "Hãy treo sẵn tờ lịch ở đằng kia nhé"},
        {"word": "飾る", "reading": "かざる", "hanviet": "SỨC", "meaning": "Trang trí", "example": "玄関に綺麗な花が飾ってあるんです", "exampleVi": "Thực ra là có hoa đẹp đang được trang trí ở lối vào đấy"},
        {"word": "並べる", "reading": "ならべる", "hanviet": "TỊNH", "meaning": "Xếp thành hàng", "example": "会議の前に椅子を並べておきます", "exampleVi": "Tôi sẽ xếp sẵn ghế trước cuộc họp"},
        {"word": "植える", "reading": "うえる", "hanviet": "THỰC", "meaning": "Trồng (cây)", "example": "庭に桜の木が植えてあるんです", "exampleVi": "Thực ra là trong vườn có trồng sẵn cây hoa anh đào đấy"},
        {"word": "戻す", "reading": "もどす", "hanviet": "LỆ", "meaning": "Đưa về, để lại vị trí ban đầu", "example": "道具を使ったら、元の場所に戻しておいてください", "exampleVi": "Nếu dùng xong dụng cụ thì hãy để lại vị trí cũ nhé"},
        {"word": "纏める", "reading": "まとめる", "hanviet": "TRIỀN", "meaning": "Tóm tắt, thu dọn, nhóm lại", "example": "レポートを書く前に、意見をまとめておきます", "exampleVi": "Tôi sẽ tóm tắt lại các ý kiến trước khi viết báo cáo"},
        {"word": "仕舞う", "reading": "しまう", "hanviet": "SĨ VŨ", "meaning": "Cất đi", "example": "大事な書類は引き出しに仕舞っておいてください", "exampleVi": "Hãy cất sẵn các giấy tờ quan trọng vào ngăn kéo nhé"},
        {"word": "決める", "reading": "きめる", "hanviet": "QUYẾT", "meaning": "Quyết định", "example": "会議の日にちを早く決めなければなりません", "exampleVi": "Tôi phải quyết định ngày họp sớm"},
        {"word": "予習する", "reading": "よしゅうする", "hanviet": "DỰ TẬP", "meaning": "Chuẩn bị bài mới", "example": "授業の前に、新しい言葉を予習しておきます", "exampleVi": "Tôi sẽ chuẩn bị trước từ mới trước giờ học"},
        {"word": "復習する", "reading": "ふくしゅうする", "hanviet": "PHỤC TẬP", "meaning": "Ôn bài cũ", "example": "習ったことを忘れないように、復習するんです", "exampleVi": "Để không quên những gì đã học, tôi thường ôn tập lại đấy"},
        {"word": "そのままにする", "reading": "そのままにする", "hanviet": "", "meaning": "Để nguyên như thế", "example": "まだ使っていますから、そのままにしておいてください", "exampleVi": "Vì tôi vẫn đang dùng nên hãy cứ để nguyên như thế nhé"},
        {"word": "授業", "reading": "じゅぎょう", "hanviet": "THỤ NGHIỆP", "meaning": "Giờ học", "example": "もうすぐ授業が始まるんです", "exampleVi": "Giờ học sắp bắt đầu rồi đấy"},
        {"word": "講義", "reading": "こうぎ", "hanviet": "GIẢNG NGHĨA", "meaning": "Bài giảng", "example": "有名な先生の講義を聞きに行くつもりです", "exampleVi": "Tôi định đi nghe bài giảng của một giáo sư nổi tiếng"},
        {"word": "ミーティング", "reading": "ミーティング", "hanviet": "", "meaning": "Cuộc họp (meeting)", "example": "仕事の前に、短いミーティングをすることになっています", "exampleVi": "Chúng tôi được quy định là sẽ có một cuộc họp ngắn trước khi làm việc"},
        {"word": "予定", "reading": "よてい", "hanviet": "DỰ ĐỊNH", "meaning": "Kế hoạch, dự định", "example": "出張の予定が決まったら、教えてください", "exampleVi": "Khi nào kế hoạch đi công tác được quyết định thì hãy bảo tôi nhé"},
        {"word": "お知らせ", "reading": "おしらせ", "hanviet": "TRI", "meaning": "Bản thông báo, tin tức", "example": "掲示板にお知らせが貼ってありますよ", "exampleVi": "Có bản thông báo đang được dán ở trên bảng tin đấy"},
        {"word": "ガイドブック", "reading": "ガイドブック", "hanviet": "", "meaning": "Sách hướng dẫn du lịch", "example": "ガイドブックを読んで、旅行の準備をしておきます", "exampleVi": "Tôi sẽ đọc sách hướng dẫn du lịch để chuẩn bị sẵn cho chuyến đi"},
        {"word": "カレンダー", "reading": "カレンダー", "hanviet": "", "meaning": "Lịch, tờ lịch", "example": "カレンダーに予定が書いてあります", "exampleVi": "Dự định đã được viết sẵn ở trên lịch"},
        {"word": "ポスター", "reading": "ポスター", "hanviet": "", "meaning": "Áp phích, poster", "example": "壁に新しい映画のポスターが貼ってあります", "exampleVi": "Một tấm áp phích phim mới đang được dán trên tường"},
        {"word": "予定表", "reading": "よていひょう", "hanviet": "DỰ ĐỊNH BIỂU", "meaning": "Lịch làm việc, thời gian biểu", "example": "予定表を見て、ミーティングの時間を決めましょう", "exampleVi": "Chúng ta hãy xem lịch làm việc rồi quyết định giờ họp nhé"},
        {"word": "ごみ箱", "reading": "ごみばこ", "hanviet": "TƯƠNG", "meaning": "Thùng rác", "example": "部屋の隅にごみ箱が置いてあります", "exampleVi": "Có một thùng rác được đặt ở góc phòng"},
        {"word": "人形", "reading": "にんぎょう", "hanviet": "NHÂN HÌNH", "meaning": "Con búp bê, con rối", "example": "棚の上に綺麗な人形が飾ってあるんです", "exampleVi": "Trên kệ có trang trí một con búp bê rất đẹp đấy"},
        {"word": "花瓶", "reading": "かびん", "hanviet": "HOA BÌNH", "meaning": "Lọ hoa", "example": "花瓶を割ってしまったので、新しいのを買わなければなりません", "exampleVi": "Vì tôi lỡ làm vỡ lọ hoa rồi nên phải mua cái mới"},
        {"word": "鏡", "reading": "かがみ", "hanviet": "KÍNH", "meaning": "Cái gương", "example": "壁に鏡が掛けてあります", "exampleVi": "Một chiếc gương đang được treo trên tường"},
        {"word": "引き出し", "reading": "ひきだし", "hanviet": "DẪN XUẤT", "meaning": "Ngăn kéo", "example": "大切な書類は引き出しに仕舞っておいてください", "exampleVi": "Hãy cất sẵn các giấy tờ quan trọng vào ngăn kéo nhé"},
        {"word": "玄関", "reading": "げんかん", "hanviet": "HUYỀN QUAN", "meaning": "Cửa vào, lối vào", "example": "玄関に誰か来ているようです", "exampleVi": "Hình như có ai đó đang đến ở cửa vào"},
        {"word": "廊下", "reading": "ろうか", "hanviet": "LANG HẠ", "meaning": "Hành lang", "example": "廊下を走らないようにしてください", "exampleVi": "Hãy chú ý đừng chạy ở hành lang nhé"},
        {"word": "壁", "reading": "かべ", "hanviet": "BÍCH", "meaning": "Bức tường", "example": "壁にポスターが貼ってあります", "exampleVi": "Tờ áp phích đang được dán trên tường"},
        {"word": "池", "reading": "いけ", "hanviet": "TRÌ", "meaning": "Cái ao", "example": "公園の池に魚がたくさん泳いでいるのが見えます", "exampleVi": "Có thể nhìn thấy rất nhiều cá đang bơi dưới ao trong công viên"},
        {"word": "元の所", "reading": "もとのところ", "hanviet": "NGUYÊN SỞ", "meaning": "Địa điểm ban đầu, chỗ cũ", "example": "辞書を使ったら、元の所に戻しておいてください", "exampleVi": "Sau khi dùng xong từ điển, hãy để lại chỗ cũ nhé"},
        {"word": "周り", "reading": "まわり", "hanviet": "CHU", "meaning": "Xung quanh", "example": "家の周りに木がたくさん植えてあります", "exampleVi": "Quanh nhà có trồng rất nhiều cây"},
        {"word": "真ん中", "reading": "まんなか", "hanviet": "CHÂN TRUNG", "meaning": "Giữa, trung tâm", "example": "テーブルの真ん中に花瓶が置いてあるんです", "exampleVi": "Thực ra là có một lọ hoa được đặt ở chính giữa bàn đấy"},
        {"word": "隅", "reading": "すみ", "hanviet": "NGUNG", "meaning": "Góc", "example": "部屋の隅に荷物が置いてあります", "exampleVi": "Hành lý đang được đặt ở góc phòng"},
        {"word": "まだ", "reading": "まだ", "hanviet": "", "meaning": "Chưa, vẫn còn", "example": "レポートはまだ書き終わっていないんです", "exampleVi": "Thật ra là tôi vẫn chưa viết xong báo cáo"},
        {"word": "リュック", "reading": "リュック", "hanviet": "", "meaning": "Ba lô", "example": "山に登るために、大きいリュックを買ったんです", "exampleVi": "Thật ra là tôi đã mua một cái ba lô lớn để leo núi"},
        {"word": "非常袋", "reading": "ひじょうぶくろ", "hanviet": "PHI THƯỜNG ĐẠI", "meaning": "Túi khẩn cấp", "example": "非常袋を準備しておいたほうがいいですよ", "exampleVi": "Bạn nên chuẩn bị sẵn một chiếc túi khẩn cấp nhé"},
        {"word": "非常時", "reading": "ひじょうじ", "hanviet": "PHI THƯỜNG THỜI", "meaning": "Trường hợp khẩn cấp, lúc khẩn cấp", "example": "非常時に使う懐中電灯はどこにありますか", "exampleVi": "Chiếc đèn pin dùng cho lúc khẩn cấp đang ở đâu vậy"},
        {"word": "生活", "reading": "せいかつ", "hanviet": "SINH HOẠT", "meaning": "Sinh hoạt, cuộc sống", "example": "日本の生活は便利だし、楽しいんです", "exampleVi": "Cuộc sống ở Nhật vừa tiện lợi lại vừa vui nữa"},
        {"word": "懐中電灯", "reading": "かいちゅうでんとう", "hanviet": "HOÀI TRUNG ĐIỆN ĐĂNG", "meaning": "Đèn pin", "example": "懐中電灯が引き出しの中に入れてあります", "exampleVi": "Chiếc đèn pin đã được để sẵn trong ngăn kéo"},
        {"word": "～とか、～とか", "reading": "～と、～とか", "hanviet": "", "meaning": "Như là, nào là", "example": "週末は掃除とか、洗濯とかをするつもりです", "exampleVi": "Cuối tuần tôi định làm những việc như dọn dẹp hay giặt giũ"},
        {"word": "丸い", "reading": "まるい", "hanviet": "HOÀN", "meaning": "Tròn", "example": "その丸い形をした家具はどこで買ったんですか", "exampleVi": "Món đồ nội thất có hình tròn đó bạn đã mua ở đâu vậy"},
        {"word": "ある～", "reading": "ある", "hanviet": "", "meaning": "Có một ~, một ~ nọ", "example": "ある日、不思議な夢を見たんです", "exampleVi": "Một ngày nọ, tôi đã mơ một giấc mơ kỳ lạ"},
        {"word": "夢を見る", "reading": "ゆめをみる", "hanviet": "MỘNG KIẾN", "meaning": "Mơ, nằm mơ", "example": "ゆうべ、怖い夢を見てしまったんです", "exampleVi": "Đêm qua tôi đã lỡ mơ một giấc mơ rất đáng sợ"},
        {"word": "嬉しい", "reading": "うれしい", "hanviet": "HI", "meaning": "Vui, hạnh phúc", "example": "合格したと聞いて、とても嬉しいです", "exampleVi": "Nghe tin đã thi đỗ tôi rất vui"},
        {"word": "嫌", "reading": "いや", "hanviet": "HIỀM", "meaning": "Ghét, chán, không thích", "example": "雨の日に出掛けるのは嫌なんです", "exampleVi": "Thật ra là tôi ghét việc phải ra ngoài vào ngày mưa"},
        {"word": "すると", "reading": "すると", "hanviet": "", "meaning": "Sau đó, rồi, ngay lập tức", "example": "ボタンを押しました。すると、電気が消えました", "exampleVi": "Tôi đã ấn nút. Sau đó thì điện tắt"},
        {"word": "目が覚める", "reading": "めがさめる", "hanviet": "MỤC GIÁC", "meaning": "Tỉnh giấc, mở mắt", "example": "5時に目が覚めてしまったんですが、まだ暗かったんです", "exampleVi": "Tôi lỡ tỉnh giấc lúc 5 giờ, nhưng lúc đó trời vẫn còn tối"},
    ],
}


